//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltiDrive
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public string guid { get; set; }
        public string origFileName { get; set; }
        public System.DateTime lastModified { get; set; }
        public string service { get; set; }
        public string serviceFileId { get; set; }
        public string rootFolder { get; set; }
        public string relativeFilePath { get; set; }
    }
}
